### PR TITLE
Document idle socket timeout.

### LINKED ISSUE #92: Document increasing (or disabling) socket timeout.
User on a slow network was getting a truncated tgz for a particularly large module. Need to document how to increase or disable idle socket timeouts.

### PR DESCRIPTION
**Pull request by jasisk**
A tiny amount of documentation.

### CODE REVIEW

**Comment by totherik** [comment]
Can you please mention shasum mismatch as a symptom?

**Comment by aredridel** [comment]
Oh nice. :+1:

**Comment by jasisk** [comment]
Yeah. Let me see if I can find the exact language.

**Comment by totherik** [comment]
:+1:

**Pull request merged**
