### PR TITLE
Fix HEAD support in Kappa

### LINKED ISSUE #99: HEAD Requests
Hey @jeffharrell, Scott from Dow Jones

 Does kappa support HEAD requests? 

I see it in the docs but not the plugin code. I have a local instance that throws 500s on HEAD and our company instance just hangs. I ask because we are migrating to artifactory and they check all the packages with HEAD before proceeding (and of course NPM supports HEAD).

### PR DESCRIPTION
**Pull request by jasisk**
We will need to revisit our `head` tests however this should solve the issue.

Fixes #99.

### CODE REVIEW

**Comment by totherik** [comment]
Do tests fail or pass with this change?

:+1:

**Comment by jasisk** [comment]
The tests used to pass. they still do, but I used to, too.

**Comment by totherik** [comment]
LGTM

**Comment by aredridel** [comment]
:+1:

**Pull request merged**
